---
title: "envirocan"
author: "Steffi LaZerte and Sam Albers"
date: "`r Sys.Date()`"
output: github_document
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



## From Environment Canada:

### Data interval

Depending on individual climate observing programs and climate elements, weather observations at a climate station are recorded at three basic intervals:

- Hourly: indicates data values for observations taken on an hourly basis.
- Daily: indicates data values for observations taken once in a 24-hour period.
- Monthly: are averages for each month, derived from daily data values.



## Types of Data

### wind speed (km/h)

The speed of motion of air in kilometres per hour (km/h) usually observed at 10 metres above the ground. It represents the average speed during the two-minute period ending at the time of observation. In observing, it is measured in nautical miles per hour or kilometres per hour.
Conversion factors:

- 1 nautical mile = 1852 metres or 1.852 km

therefore:

- 1 knot = 1.852 km/h

and

- 1 km/h = 0.54 knot.



Also a quote using `>`:

> "He who gives up [code] safety for [code] speed deserves neither."
([via](https://twitter.com/hadleywickham/status/504368538874703872))
