---
title: "Weather: Terms and Units"
author: "Steffi LaZerte"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Weather: Terms and Units}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
library(weathercan)
library(dplyr)
```

This table shows details regarding original column (measurement) names and units of all weather measurements. It further provides links back to the ECCC glossary for more details.

For details on climate normals measurements, see the `glossary_normals` vignette.

```{r, asis = TRUE, echo = FALSE}
temp <- glossary %>%
  mutate(http = stringr::str_detect(ECCC_ref, "http"),
         ECCC_ref = replace(ECCC_ref, http & !is.na(http), paste0("[ECCC glossary page](", ECCC_ref[http & !is.na(http)], ")")),
         ECCC_ref = replace(ECCC_ref, !http & !is.na(http), "[See the 'flags' vignette](flags.html)")) %>%
  select(Interval = interval, `ECCC Name` = ECCC_name, `Formatted weathercan name` = weathercan_name, units, Reference = ECCC_ref)
  
knitr::kable(temp)
```
